name: demoFTP

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  demo:
    runs-on: windows-latest

    steps:
      - name: Ping servidor
        run: ping -n 4 38.253.154.34

      - name: Ver puertos abiertos
        run: netstat -ano

      
